
-- -------------------------------------------------------------------
-- Script Name: hello_github.sql
-- Description: A sample Oracle SQL script to upload to GitHub.
-- Author: Your Name
-- Date: 2026-08-24
-- -------------------------------------------------------------------

-- Set standard SQL*Plus environment variables
SET ECHO ON;
SET SERVEROUTPUT ON;

-- Create a sample table
CREATE TABLE github_projects (
    project_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name VARCHAR2(100) NOT NULL,
    language     VARCHAR2(50),
    created_date DATE DEFAULT SYSDATE
);

-- Insert sample data
INSERT INTO github_projects (project_name, language) VALUES ('Sample Perl Script', 'Perl');
INSERT INTO github_projects (project_name, language) VALUES ('Sample Shell Script', 'Bash');
INSERT INTO github_projects (project_name, language) VALUES ('Sample Oracle Script', 'SQL');

-- Commit the transaction
COMMIT;

-- Query the table to verify data
SELECT project_id, project_name, language, TO_CHAR(created_date, 'YYYY-MM-DD') AS created_on
FROM github_projects;

-- Output a success message using an anonymous PL/SQL block
BEGIN
    DBMS_OUTPUT.PUT_LINE('----------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('Sample data inserted and queried successfully!');
    DBMS_OUTPUT.PUT_LINE('Hello, GitHub!');
    DBMS_OUTPUT.PUT_LINE('----------------------------------------------------');
END;
/
